enum {
    SYSLOG_TYPE_SYSTEM,
    SYSLOG_TYPE_SETUP,
    SYSLOG_TYPE_SEARCH,
    SYSLOG_TYPE_OPERATION,
    SYSLOG_TYPE_EVENT,
    SYSLOG_TYPE_CAMERA,
    SYSLOG_TYPE_PTZ,
    SYSLOG_TYPE_BACKUP,
    SYSLOG_TYPE_RECYCLE,
    SYSLOG_TYPE_NTP,
    SYSLOG_TYPE_NETWORK,
    SYSLOG_TYPE_MAX_NUM
};

enum {
    SYSLOG_PARAM_POWER_ON,
    SYSLOG_PARAM_POWER_OFF,
    SYSLOG_PARAM_NTP_ACCESS_FAIL,
    SYSLOG_PARAM_NTP_ADJUST_FAIL,
    SYSLOG_PARAM_NTP_NEED_NOT_ADJUST,
    SYSLOG_PARAM_NTP_NEED_TO_CHECK,
    SYSLOG_PARAM_NTP_ADJUSTED,
    SYSLOG_PARAM_NTP_REBOOT,
    SYSLOG_PARAM_NTP_ADJUSTED_FORWARD,
    SYSLOG_PARAM_NTP_ADJUSTED_BACKWARD,
    SYSLOG_SYSTEM_PARAM_MAX_NUM
};

enum {
    SYSLOG_PARAM_SETUP_ENTER,
    SYSLOG_PARAM_SETUP_EXIT,
    SYSLOG_PARAM_DISPLAY_CHANGED,
    SYSLOG_PARAM_RECORD_CHANGED,
    SYSLOG_PARAM_DEVICE_CHANGED,
    SYSLOG_PARAM_SYSTEM_CHANGED,
    SYSLOG_PARAM_STORAGE_CHANGED,
    SYSLOG_PARAM_RECORD_RESOLUTION_QUATER,
    SYSLOG_PARAM_RECORD_RESOLUTION_HALF,
    SYSLOG_PARAM_RECORD_RESOLUTION_FULL,
    SYSLOG_PARAM_RECORD_FRAMERATE,
    SYSLOG_PARAM_RECORD_QUALITY_ECONOMY,
    SYSLOG_PARAM_RECORD_QUALITY_STANDARD,
    SYSLOG_PARAM_RECORD_QUALITY_HIGH,
    SYSLOG_PARAM_RECORD_QUALITY_SUPER,
    SYSLOG_PARAM_RECORD_DISABLE,
    SYSLOG_PARAM_RECORD_CONTINUOUS,
    SYSLOG_PARAM_RECORD_MOTION,
    SYSLOG_PARAM_RECORD_SENSOR,
    SYSLOG_PARAM_RECORD_SCHEDULE,
    SYSLOG_PARAM_DEVICE_PARTIAL_ZONE,
    SYSLOG_PARAM_DEVICE_FULL_ZONE,
    SYSLOG_PARAM_WEBSETUP_APPLY,
    SYSLOG_SETUP_PARAM_MAX_NUM
};

enum {
    SYSLOG_SEARCH_PARAM_MAX_NUM
};

enum {
    SYSLOG_PARAM_MANUAL_REC_ON,
    SYSLOG_PARAM_MANUAL_REC_OFF,
    SYSLOG_OPERATION_PARAM_MAX_NUM
};

enum {
    SYSLOG_PARAM_VIDEO_LOSS,
    SYSLOG_PARAM_VIDEO_IN,
    SYSLOG_PARAM_UNSTABLE_VIDEO,
    SYSLOG_EVENT_PARAM_MAX_NUM
};

enum {
    SYSLOG_PARAM_NETWORK_CONNECT,
    SYSLOG_PARAM_NETWORK_DISCONNECT,
    SYSLOG_NETWORK_PARAM_MAX_NUM
};
