#!/bin/sh

/sbin/bootmode

mount -t yaffs2 /dev/mtdblock2 /cfg
mount -t yaffs2 /dev/mtdblock8 /misc

touch /tmp/resolv.conf
chmod 755 /tmp/resolv.conf

PATH="/usr/bin:/usr/sbin:/bin:/sbin"
LD_LIBRARY_PATH="/usr/local/lib:/usr/lib"
export PATH
export LD_LIBRARY_PATH
export QT_PLUGIN_PATH=/lib

/usr/sysinit.sh
